name: OWASP ZAP Scan

on:
  workflow_run:
    workflows: ["Snyk Scan"]
    types:
      - completed

jobs:
  zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    if: always() # Run even if previous workflow failed
    steps:
      - uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.zaproxy.org'