name: Snyk Scan

on:
  workflow_run:
    workflows: ["SonarQube Scan"]
    types:
      - completed

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest
    if: always() # Run even if previous workflow failed
    steps:
      - uses: actions/checkout@v4
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}